services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    env_file: .env
  webapp:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres